module MakeProxies where

import Data.Proxy(Proxy(..))
import ChessTypes
import FirstClassFunctions
import qualified GHC.TypeLits as TL
import Data.Type.Nat hiding (SNat(..))

-- Transform various types into singleton types (for use at the value-level)

a1 :: Proxy ('At A Nat1)
a1 = Proxy @('At A Nat1)
a2 :: Proxy ('At A Nat2)
a2 = Proxy @('At A Nat2)
a3 :: Proxy ('At A Nat3)
a3 = Proxy @('At A Nat3)
a4 :: Proxy ('At A Nat4)
a4 = Proxy @('At A Nat4)
a5 :: Proxy ('At A Nat5)
a5 = Proxy @('At A Nat5)
a6 :: Proxy ('At A Nat6)
a6 = Proxy @('At A Nat6)
a7 :: Proxy ('At A Nat7)
a7 = Proxy @('At A Nat7)
a8 :: Proxy ('At A Nat8)
a8 = Proxy @('At A Nat8)

_11 :: Proxy ('At A Nat1)
_11 = Proxy @('At A Nat1)
_12 :: Proxy ('At A Nat2)
_12 = Proxy @('At A Nat2)
_13 :: Proxy ('At A Nat3)
_13 = Proxy @('At A Nat3)
_14 :: Proxy ('At A Nat4)
_14 = Proxy @('At A Nat4)
_15 :: Proxy ('At A Nat5)
_15 = Proxy @('At A Nat5)
_16 :: Proxy ('At A Nat6)
_16 = Proxy @('At A Nat6)
_17 :: Proxy ('At A Nat7)
_17 = Proxy @('At A Nat7)
_18 :: Proxy ('At A Nat8)
_18 = Proxy @('At A Nat8)

b1 :: Proxy ('At B Nat1)
b1 = Proxy @('At B Nat1)
b2 :: Proxy ('At B Nat2)
b2 = Proxy @('At B Nat2)
b3 :: Proxy ('At B Nat3)
b3 = Proxy @('At B Nat3)
b4 :: Proxy ('At B Nat4)
b4 = Proxy @('At B Nat4)
b5 :: Proxy ('At B Nat5)
b5 = Proxy @('At B Nat5)
b6 :: Proxy ('At B Nat6)
b6 = Proxy @('At B Nat6)
b7 :: Proxy ('At B Nat7)
b7 = Proxy @('At B Nat7)
b8 :: Proxy ('At B Nat8)
b8 = Proxy @('At B Nat8)

_21 :: Proxy ('At B Nat1)
_21 = Proxy @('At B Nat1)
_22 :: Proxy ('At B Nat2)
_22 = Proxy @('At B Nat2)
_23 :: Proxy ('At B Nat3)
_23 = Proxy @('At B Nat3)
_24 :: Proxy ('At B Nat4)
_24 = Proxy @('At B Nat4)
_25 :: Proxy ('At B Nat5)
_25 = Proxy @('At B Nat5)
_26 :: Proxy ('At B Nat6)
_26 = Proxy @('At B Nat6)
_27 :: Proxy ('At B Nat7)
_27 = Proxy @('At B Nat7)
_28 :: Proxy ('At B Nat8)
_28 = Proxy @('At B Nat8)

c1 :: Proxy ('At C Nat1)
c1 = Proxy @('At C Nat1)
c2 :: Proxy ('At C Nat2)
c2 = Proxy @('At C Nat2)
c3 :: Proxy ('At C Nat3)
c3 = Proxy @('At C Nat3)
c4 :: Proxy ('At C Nat4)
c4 = Proxy @('At C Nat4)
c5 :: Proxy ('At C Nat5)
c5 = Proxy @('At C Nat5)
c6 :: Proxy ('At C Nat6)
c6 = Proxy @('At C Nat6)
c7 :: Proxy ('At C Nat7)
c7 = Proxy @('At C Nat7)
c8 :: Proxy ('At C Nat8)
c8 = Proxy @('At C Nat8)

_31 :: Proxy ('At C Nat1)
_31 = Proxy @('At C Nat1)
_32 :: Proxy ('At C Nat2)
_32 = Proxy @('At C Nat2)
_33 :: Proxy ('At C Nat3)
_33 = Proxy @('At C Nat3)
_34 :: Proxy ('At C Nat4)
_34 = Proxy @('At C Nat4)
_35 :: Proxy ('At C Nat5)
_35 = Proxy @('At C Nat5)
_36 :: Proxy ('At C Nat6)
_36 = Proxy @('At C Nat6)
_37 :: Proxy ('At C Nat7)
_37 = Proxy @('At C Nat7)
_38 :: Proxy ('At C Nat8)
_38 = Proxy @('At C Nat8)

d1 :: Proxy ('At D Nat1)
d1 = Proxy @('At D Nat1)
d2 :: Proxy ('At D Nat2)
d2 = Proxy @('At D Nat2)
d3 :: Proxy ('At D Nat3)
d3 = Proxy @('At D Nat3)
d4 :: Proxy ('At D Nat4)
d4 = Proxy @('At D Nat4)
d5 :: Proxy ('At D Nat5)
d5 = Proxy @('At D Nat5)
d6 :: Proxy ('At D Nat6)
d6 = Proxy @('At D Nat6)
d7 :: Proxy ('At D Nat7)
d7 = Proxy @('At D Nat7)
d8 :: Proxy ('At D Nat8)
d8 = Proxy @('At D Nat8)

_41 :: Proxy ('At D Nat1)
_41 = Proxy @('At D Nat1)
_42 :: Proxy ('At D Nat2)
_42 = Proxy @('At D Nat2)
_43 :: Proxy ('At D Nat3)
_43 = Proxy @('At D Nat3)
_44 :: Proxy ('At D Nat4)
_44 = Proxy @('At D Nat4)
_45 :: Proxy ('At D Nat5)
_45 = Proxy @('At D Nat5)
_46 :: Proxy ('At D Nat6)
_46 = Proxy @('At D Nat6)
_47 :: Proxy ('At D Nat7)
_47 = Proxy @('At D Nat7)
_48 :: Proxy ('At D Nat8)
_48 = Proxy @('At D Nat8)

e1 :: Proxy ('At E Nat1)
e1 = Proxy @('At E Nat1)
e2 :: Proxy ('At E Nat2)
e2 = Proxy @('At E Nat2)
e3 :: Proxy ('At E Nat3)
e3 = Proxy @('At E Nat3)
e4 :: Proxy ('At E Nat4)
e4 = Proxy @('At E Nat4)
e5 :: Proxy ('At E Nat5)
e5 = Proxy @('At E Nat5)
e6 :: Proxy ('At E Nat6)
e6 = Proxy @('At E Nat6)
e7 :: Proxy ('At E Nat7)
e7 = Proxy @('At E Nat7)
e8 :: Proxy ('At E Nat8)
e8 = Proxy @('At E Nat8)

_51 :: Proxy ('At E Nat1)
_51 = Proxy @('At E Nat1)
_52 :: Proxy ('At E Nat2)
_52 = Proxy @('At E Nat2)
_53 :: Proxy ('At E Nat3)
_53 = Proxy @('At E Nat3)
_54 :: Proxy ('At E Nat4)
_54 = Proxy @('At E Nat4)
_55 :: Proxy ('At E Nat5)
_55 = Proxy @('At E Nat5)
_56 :: Proxy ('At E Nat6)
_56 = Proxy @('At E Nat6)
_57 :: Proxy ('At E Nat7)
_57 = Proxy @('At E Nat7)
_58 :: Proxy ('At E Nat8)
_58 = Proxy @('At E Nat8)

f1 :: Proxy ('At F Nat1)
f1 = Proxy @('At F Nat1)
f2 :: Proxy ('At F Nat2)
f2 = Proxy @('At F Nat2)
f3 :: Proxy ('At F Nat3)
f3 = Proxy @('At F Nat3)
f4 :: Proxy ('At F Nat4)
f4 = Proxy @('At F Nat4)
f5 :: Proxy ('At F Nat5)
f5 = Proxy @('At F Nat5)
f6 :: Proxy ('At F Nat6)
f6 = Proxy @('At F Nat6)
f7 :: Proxy ('At F Nat7)
f7 = Proxy @('At F Nat7)
f8 :: Proxy ('At F Nat8)
f8 = Proxy @('At F Nat8)

_61 :: Proxy ('At F Nat1)
_61 = Proxy @('At F Nat1)
_62 :: Proxy ('At F Nat2)
_62 = Proxy @('At F Nat2)
_63 :: Proxy ('At F Nat3)
_63 = Proxy @('At F Nat3)
_64 :: Proxy ('At F Nat4)
_64 = Proxy @('At F Nat4)
_65 :: Proxy ('At F Nat5)
_65 = Proxy @('At F Nat5)
_66 :: Proxy ('At F Nat6)
_66 = Proxy @('At F Nat6)
_67 :: Proxy ('At F Nat7)
_67 = Proxy @('At F Nat7)
_68 :: Proxy ('At F Nat8)
_68 = Proxy @('At F Nat8)

g1 :: Proxy ('At G Nat1)
g1 = Proxy @('At G Nat1)
g2 :: Proxy ('At G Nat2)
g2 = Proxy @('At G Nat2)
g3 :: Proxy ('At G Nat3)
g3 = Proxy @('At G Nat3)
g4 :: Proxy ('At G Nat4)
g4 = Proxy @('At G Nat4)
g5 :: Proxy ('At G Nat5)
g5 = Proxy @('At G Nat5)
g6 :: Proxy ('At G Nat6)
g6 = Proxy @('At G Nat6)
g7 :: Proxy ('At G Nat7)
g7 = Proxy @('At G Nat7)
g8 :: Proxy ('At G Nat8)
g8 = Proxy @('At G Nat8)

_71 :: Proxy ('At G Nat1)
_71 = Proxy @('At G Nat1)
_72 :: Proxy ('At G Nat2)
_72 = Proxy @('At G Nat2)
_73 :: Proxy ('At G Nat3)
_73 = Proxy @('At G Nat3)
_74 :: Proxy ('At G Nat4)
_74 = Proxy @('At G Nat4)
_75 :: Proxy ('At G Nat5)
_75 = Proxy @('At G Nat5)
_76 :: Proxy ('At G Nat6)
_76 = Proxy @('At G Nat6)
_77 :: Proxy ('At G Nat7)
_77 = Proxy @('At G Nat7)
_78 :: Proxy ('At G Nat8)
_78 = Proxy @('At G Nat8)

h1 :: Proxy ('At H Nat1)
h1 = Proxy @('At H Nat1)
h2 :: Proxy ('At H Nat2)
h2 = Proxy @('At H Nat2)
h3 :: Proxy ('At H Nat3)
h3 = Proxy @('At H Nat3)
h4 :: Proxy ('At H Nat4)
h4 = Proxy @('At H Nat4)
h5 :: Proxy ('At H Nat5)
h5 = Proxy @('At H Nat5)
h6 :: Proxy ('At H Nat6)
h6 = Proxy @('At H Nat6)
h7 :: Proxy ('At H Nat7)
h7 = Proxy @('At H Nat7)
h8 :: Proxy ('At H Nat8)
h8 = Proxy @('At H Nat8)

_81 :: Proxy ('At H Nat1)
_81 = Proxy @('At H Nat1)
_82 :: Proxy ('At H Nat2)
_82 = Proxy @('At H Nat2)
_83 :: Proxy ('At H Nat3)
_83 = Proxy @('At H Nat3)
_84 :: Proxy ('At H Nat4)
_84 = Proxy @('At H Nat4)
_85 :: Proxy ('At H Nat5)
_85 = Proxy @('At H Nat5)
_86 :: Proxy ('At H Nat6)
_86 = Proxy @('At H Nat6)
_87 :: Proxy ('At H Nat7)
_87 = Proxy @('At H Nat7)
_88 :: Proxy ('At H Nat8)
_88 = Proxy @('At H Nat8)

_Knight :: Proxy ('Knight)
_Knight = Proxy @Knight
_N = _Knight
__4 = _N

_Rook :: Proxy ('Rook)
_Rook = Proxy @Rook
_R = _Rook
__2 = _R

_Bishop :: Proxy ('Bishop)
_Bishop = Proxy @Bishop
_B = _Bishop
__3 = _B

_Queen :: Proxy ('Queen)
_Queen = Proxy @Queen
_Q = _Queen
__1 = _Q

_Pawn :: Proxy ('Pawn)
_Pawn = Proxy @Pawn
_P = _Pawn

_King :: Proxy ('King)
_King = Proxy @King
_K = _King

white :: Proxy ('White)
white = Proxy @White
_Wh = white

black :: Proxy ('Black)
black = Proxy @Black
_Bl = black
